version: "3.9"

services:
  backend:
    build:
      context: ../nano-task-manager-api
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ../nano-task-manager-api/.env
    networks:
      - app-network

  frontend:
    build:
      context: ../nano-task-manager
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
